services:
  - type: web
    name: ai-assistant
    env: node
    buildCommand: npm run build
    startCommand: npm run server
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 